FROM oven/bun:1.2.18-alpine AS base

WORKDIR /app

# COPY package*.json bun.lock tsconfig.app.json tsconfig.json tsconfig.node.json vite.config.ts ./
#
# RUN bun install
#
# COPY ./src ./src
#
# COPY ./public ./public
#
# COPY index.html index.html

ARG UI_PORT

ARG API_HOST

ARG API_PORT

ENV UI_PORT=$UI_PORT

ENV VITE_API_HOST=$API_HOST

ENV VITE_API_PORT=$API_PORT

CMD ["bun", "run", "dev","--host"]


