const STRINGS = {
  yes: "نعم",
  no: "لا",
  phone_number: "رقم الهاتف",
  view: "عرض",
  add: "إضافة",
  edit: "تعديل",
  save: "حفظ",
  password: "كلمة المرور",
  login: "تسجيل الدخول",
  logout: "تسجيل الخروج",
  disclosures: "الكشوفات",
  priority: "الأولية",
  created_at: "تاريخ الإنشاء",
  disclosure_created_at: "تاريخ إضافة الكشف",
  disclosure_scout: "الكشاف",
  updated_at: "تاريخ اخر تعديل",
  patient_address: "العنوان التفصيلي",
  status: "الحالة",
  active: "نشط",
  app_data: "البيانات",
  canceled: "ملغى",
  cancel: "إلغاء",
  finished: "مكتمل",
  phones: "ارقام الهاتف",
  name: "الاسم",
  phone_numbers: "أرقام الهاتف",
  patient_about: "ملاحظة حول المستفيد",
  national_number: "الرقم الوطني",
  city: "المدينة",
  cities: "المدن",
  area: "المنطقة",
  areas: "المناطق",
  ratings: "التقييمات",
  rating: "التقييم",
  add_rating: "إضافة تقييم",
  add_visit: "إضافة زيارة",
  is_custom_rating: "تقييم مخصص ؟",
  the_custom_rating: "التقيم المخصص",
  custom_rating: "تقيم مخصص",
  visits: "الزيارات",
  added_successfully: "تمت الإضافة بنجاح",
  edited_successfully: "تم التعديل بنجاح",
  something_went_wrong: "حصل خطأ ما",
  beneficiaries: "المتسفيدين",
  beneficiary: "المستفيد",
  employees: "الموظفين",
  employee: "الموظف",
  add_beneficiary: "إضافة مستفيد",
  add_employee: "إضافة موظف",
  no_data_found: "لم يتم العثور على اي بيانات",
  beneficiary_doesnt_have_any_disclosure: "لايملك هذا المستفيد اي كشف",
  manager: "إداري",
  supervisor: "مشرف",
  scout: "كشاف",
  the_scout: "الكشاف",
  role: "المنصب",
  none: "لا يوجد",
  priority_degree: "درجة الأهمية",
  cant_be_completed: "لايمكن إكمالها",
  not_completed: "غير مكتملة",
  completed: "مكتملة",
  note: "ملاحظة",
  description: "الوصف",
  code: "الرمز",
  visit_result: "نتيجة الزيارة",
  visit_reason: "السبب",
  sync: "المزامنة",
  from_date: "من تاريخ",
  to_date: "الى تاريخ",
  search: "بحث",
};

export default STRINGS;
