const STRINGS = {
  yes: 'نعم',
  no: 'لا',
  phone_number: 'رقم الهاتف',
  view: 'عرض',
  add: 'إضافة',
  edit: 'تعديل',
  save: 'حفظ',
  password: 'كلمة المرور',
  login: 'تسجيل الدخول',
  logout: 'تسجيل الخروج',
  disclosures: 'الكشوفات',
  priority: 'الأولية',
  created_at: ' تاريخ الإضافة',
  and: 'و',
  Patient_created_at: ' تاريخ اضافة المستفيد',
  disclosure_created_at: 'تاريخ إضافة الكشف',
  disclosure_updated_at: 'تاريح اخر تعديل للكشف',
  disclosure_scout: 'الكشّاف',
  updated_at: 'تاريخ اخر تعديل',
  patient_updated_at: 'تاريخ اخر تعديل للمستفيد',
  patient_address: 'العنوان التفصيلي',
  status: 'الحالة',
  active: 'نشط',
  suspended: 'موقّف',
  archived: 'مؤرشف',
  delete: 'حذف',
  result: 'النتيجة',
  app_data: 'البيانات',
  cancel: 'إلغاء',
  phones: 'ارقام الهاتف',
  name: 'الاسم',
  phone_numbers: 'أرقام الهاتف',
  patient_about: 'ملاحظة حول المستفيد',
  national_number: 'الرقم الوطني',
  city: 'المدينة',
  cities: 'المدن',
  area: 'المنطقة',
  areas: 'المناطق',
  ratings: 'التقييمات',
  rating: 'التقييم',
  add_rating: 'إضافة تقييم',
  add_visit: 'إضافة زيارة',
  add_disclosure: 'إضافة كشف',
  filter: 'فلترة',
  is_custom_rating: 'تقييم مخصص ؟',
  the_custom_rating: 'التقيم المخصص',
  custom_rating: 'تقييم مخصص',
  visits: 'الزيارات',
  added_successfully: 'تمت الإضافة بنجاح',
  edited_successfully: 'تم التعديل بنجاح',
  action_done_successfully: 'تمة العملية بنجاح',
  something_went_wrong: 'حصل خطأ ما',
  beneficiaries: 'المتسفيدين',
  beneficiary: 'المستفيد',
  employees: 'الموظفين',
  employee: 'الموظّف',
  add_beneficiary: 'إضافة مستفيد',
  add_employee: 'إضافة موظف',
  no_data_found: 'لم يتم العثور على اي بيانات',
  beneficiary_doesnt_have_any_disclosure: 'لايملك هذا المستفيد اي كشف',
  manager: 'إداري',
  supervisor: 'مشرف',
  scout: 'كشّاف',
  the_scout: 'الكشّاف',
  role: 'المنصب',
  none: 'لا يوجد',
  priority_degree: 'درجة الأهمية',
  cant_be_completed: 'لايمكن إكمالها',
  not_completed: 'غير مكتملة',
  completed: 'مكتملة',
  note: 'ملاحظة',
  initial_note: ' ملاحظة اولية للكشف',
  notes: 'ملاحظات',
  description: 'الوصف',
  code: 'الرمز',
  visit_result: 'نتيجة الزيارة',
  visit_reason: 'السبب',
  sync: 'المزامنة',
  from_date: 'من تاريخ',
  to_date: 'الى تاريخ',
  search: 'بحث',
  undelivered: 'غير مسلّمة',
  city_management: 'ادارة المدن',
  add_and_manage_cities: 'اضافة وادارة المدن',
  search_city: 'ابحث عن مدينة',
  no_cities_found: 'لاتوجد اي مدينة',
  add_to_see: 'اضف بيانات لتظهر هنا',
  add_city: 'اضف مدينة',
  no_work_areas_found: 'لاتوجد اي منطقة',
  edit_city: 'تعديل مدينة',
  city_name: 'اسم المدينة',
  local_not_found_error: 'لم يتم العثور على بيانات لعرضها',
  // created_by: "تمّت الإضافة من قبل",
  // updated_by: "تمّ التعديل من قبل",
  by: 'من قِبل',
  work_areas: 'ادارة المناطق',
  work_areas_subtitle: 'ادارة وتنظيم المناطق',
  search_work_area: 'ابحث عن منطقة ...',
  work_area_name: 'اسم المنطقة',
  edit_work_area: 'تعديل المنطقة',
  add_work_area: 'اضافة منطقة',
  ratings_management: 'ادارة التقيمات',
  add_manage_ratings: 'اضافة وادرة التقيمات',
  no_ratings_found: 'لا اتوجد اي تقيمات',
  edit_rating: 'تعديل التقيم',
  priority_degrees: 'درجة الاهمية',
  add_manage_priority_degrees: 'اضافة وادراة درجة الاهمية',
  search_priority_degree: 'ابحث عن درجة اهمية....',
  edit_priority_degree: 'تعديل درجة الاهمية',
  add_priority_degree: 'اضافة درجة الاهمية',
  select_color_optional: 'اختر لون',
  quick_access: 'اختبار سريع',
  added_disclosures: 'الكشوفات المضافة',
  completed_visits: 'الزيارات المكتملة',
  not_completed_visits: 'الزيارات غير المكتملة',
  couldnt_be_completed_visits: 'الزيارات التي لم يمكن إكمالها',
  this_week: 'هذا الاسبوع',
  this_month: 'هذا الشهر',
  this_year: 'هذه السنة',
  custom: 'مخصّصّ',
  summary: 'ملخّص',
  detailed: 'مفصّل',
  time_period: 'الفترة الزمنيّة',
  satistics_type: 'نوع الإحصائية',
  home_page: 'الصفحة الرئيسيّة',
  medicines: 'الأدوية',
  med_form: 'الاستخدام',
  dose_variants: 'الجرعات',
  no_medicines_found: 'لا يوجد ادوية',
  medicines_management: 'ادارة الادوية',
  add_manage_medicines: 'اضافة و ادارة الأدوية',
  search_med: 'ابحث عن دواء ...',
  add_medicine: 'اضافة دواء',
  edit_medicine: 'تعديل دواء',
  select_one_or_more_doses: 'اختر جرعة او اكثر',
  intake_frequency_per_day: 'عدد مرات في اليوم',
  dose: 'الجرعة',
  add_beneficiary_medicine: 'اضافة دواء لمريض',
  edit_beneficiary_medicine: 'تعديل دواء مريض',
  dose_per_intake: 'معيار الجرعة',
  appointment_not_completed: 'لم تتمّ المراجعة بعد',
  appointment_completed: 'تمّت المراجعة',
  appointment_date: 'تاريخ المراجعة',
  family_members: 'أفراد العائلة',
  add_family_member: 'اضافة فرد عائلة',
  edit_family_member: 'تعديل فرد عائلة',
  birth_date: 'تاريخ الميلاد',
  job_or_school: 'العمل / الدراسة',
  gender: 'الجنس',
  kinship: 'القرابة',
  male: 'ذكر',
  female: 'انثى',
  kinship_partner: 'شريك/ة',
  kinship_child: 'ابن/ة',
  kinship_parent: 'اهل',
  kinship_brother: 'اخ/ت',
  kinship_grandparent: 'جد/ة',
  kinship_grandchild: 'حفيد/ة',
  appointment: 'المراجعة',
  add_disclosure_appointment: 'اضافة موعد زيارة',
  selected_date_cap_warning: 'يوجد العديد من المراجعات في هذا اليوم !!!',
  select_appointment_date: 'أختر يوم للمراجعة',
  edit_appointment_date: 'تعديل يوم المراجعة',
  warning: 'انتبه',
  appointment_warning_message: 'تجنبا للضغط يفضل اختيار تاريخ باقل عدد من المراجعين',
  med_form_pill: 'حب (اقراص)',
  med_form_syrup: 'شراب',
  med_form_injection: 'ابر (حقن)',
  med_form_capsule: 'كبسولة',
  med_form_ointment: 'مراهم',
  calendar: 'التقويم',
  details: 'التفاصيل',
  meetings: 'الاجتماعات',
  audience_all: 'الكل',
  audience_scouts: 'الكشاف',
  audience_supervisors: 'المشرف',
  audience: 'المستهدف',
  title: 'النص',
  type: 'النوع',
  broadcast_type_meeting: 'اجتماع',
  broadcast_type_custom: 'مخصص',
  add_manage_meetings: 'اضافة وادارة الاجتماعات',
  meetings_management: 'ادراة الاجتماعات',
  edit_meeting: 'تعديل اجتماع',
  add_meeting: 'اضافة اجتماع',
  date: 'التاريخ',
  add_disclosure_note: 'اضافة ملاحظة',
  add_note: 'اضافة ملاحطة',
  edit_note: 'تعديل ملاحظة',
  no_access: 'ليس لديك الصلاحية للقيام بذلك',
  created_By: 'المنشئ',
  unknown: 'غير معروف',
  old: 'القديم',
  new: 'جديد',
  changes: 'تغيرات',
  view_audit_log: 'عرض التغيرات',
  audit_log: 'تغيرات الكشف',
  disclosure: 'الكشف',
  changes_at: 'تم العملية بوقت',
  view_details: 'رؤية التفاصيل',
  file_too_large: 'الملف اكبر من الحد المسموح',
  record_audio: 'تسجيل صوت',
  start_recording: 'بدء التسجيل',
  stop_recording: 'انهاء التجسيل',
  upload_audio: 'رفع ملف',
  clear: 'مسح',
  audio_help_text: 'يمكن رفع نص و ملف صوتي معا',
  recorded_audio: 'تسجيل صوتي',
  consulting_adviser: 'استشارة المدير',
  disclosure_consulting: 'استشارة الكشوفات',
  consulting_adviser_pending: 'بالانتظار التحقق',
  consulting_adviser_completed: 'منتهي',
  cutom_rating: 'تقييم مخصص',
  visit: 'الزيارة',
  is_received: 'تم الاستلام',
  the_receive: 'الاستلام',
  patient: 'المستفيد',
  residential: 'المسكن',
  home_condition: 'حالة السكن',
  electricity: 'الكهرباء / الامبير',
  expenses: 'المصروف',
  disclosures_details: 'تفاصيل الكشف',
  pons: 'الإجابيات',
  cons: 'السلبيات',
  help: 'مساعدة',
  return: 'إعادة',
  close: 'إغلاق',
  last_visit_result: 'نتيجة اخر زيارة',
  last_rating_result: 'نتيجة اخر تقييم',
  hasnt_been_visited_yet: 'لم تتم الزيارة بعد',
  hasnt_been_rated_yet: 'لم يتم التقييم بعد',
  hasnt_been_received_yet: 'لم يتم الاستلام بعد',
  hg: 'حجة',
  hg_plus: 'حجة +',
  no_details: 'لايوجد تفاصيل لهذا الكشف',
  no_notes: 'لايوجد ملاحظات لهذا الكشف',
  no_family_members: 'لا يوجد أفراد عائلة لهذا المستفيد',
  disclosure_properties: 'خصائص الكشف',
  edit_done: 'تم تعديل',
  home_condition_status: 'حالة السكن',
  home_status: 'وضع الملكية',
  home_status_note: 'ملاحظة وضع الملكية',
  update_column_rating_id: 'التقيم',
  update_column_is_custom_rating: 'التقييم المخصص',
  update_column_rating_note: 'ملاحظة الزيارة',
  update_column_visit_result: 'نتيجة الزيارة',
  update_column_visit_reason: 'سبب الزيارة',
  update_column_visit_note: 'ملاحظة الزيارة',
  update_column_priority_id: 'درحة الاهمية',
  update_column_scout_id: 'الكشاف',
  update_column_is_appointment_completed: 'حالة المراجعة',
  update_column_appointment_date: 'تاريخ المراجة',
  update_column_is_received: 'حالة الاستلام',
  update_column_status: 'الحالة',
  update_column_type: 'النوع',
  update_column_initial_note: 'الملاحظة الاولية',
  update_column_custom_rating: 'التقييم المخصص',
  update_column_archive_number: 'رقم الارشفة',
  update_column_details: 'التفاصيل',
  update_column_disclosure_notes: 'ملاحظات الكشف',
  audit_details: 'تفاصيل تغيرات الكشف',
  update_column_action_insert: 'اضافة',
  update_column_action_update: 'تعديل',
  update_column_action_delete: 'حدف',
  update_column_action_defaut: 'عادي',
  old_value: 'القيمة القديمة',
  new_value: 'القيمة الجديدة',
  common_true: 'صح',
  common_false: 'خظأ',
  common_bad: 'سيئ',
  common_normal: 'عادي',
  common_good: 'جيد',
  common_excellent: 'ممتاز',
  custom_dose: 'جرعة مخصص (mg)',
  rating_available_when_visit_completed:
    'يكمن اخيتار تقييم عندما تكون الزيارة مكتملة ولا يوجد استشارة مدير غير منتهية (معلقة) لهذا الكشف',
  patient_or_surgeries: 'المريض / العمليات',
  confirm: 'تأكيد',
  r_u_sure: 'هل انت متاكد',
  receive_disclosure_confirmation: 'هل تريد استلام هذا الكشف ؟',
  complete_appointment_confirmation: ' هل تريد اتمام المراجعة ؟',
  common_loan: 'اعارة',
  common_rent: 'أجار',
  common_ownership: 'ملك',
  quick_rate: 'تقييم سريع',
  select_rating_quickly: 'اختار تقييم سريع',
  rate_patient: 'تقييم هذا المريض',
  disclosure_is_received_status: 'حالة استلام الكشف',
  disclosure_appointment_status: 'حالة المراجعة',
  install_application: 'تثبيت التطبيق',
};

export default STRINGS;
