const STRINGS = {
  yes: "نعم",
  no: "لا",
  phone_number: "رقم الهاتف",
  view: "عرض",
  add: "إضافة",
  edit: "تعديل",
  save: "حفظ",
  password: "كلمة المرور",
  login: "تسجيل الدخول",
  logout: "تسجيل الخروج",
  disclosures: "الكشوفات",
  priority: "الأولية",
  created_at: "تاريخ الإضافة",
  disclosure_created_at: "تاريخ إضافة الكشف",
  disclosure_scout: "الكشّاف",
  updated_at: "تاريخ اخر تعديل",
  patient_address: "العنوان التفصيلي",
  status: "الحالة",
  active: "نشط",
  delete: "حذف",
  app_data: "البيانات",
  canceled: "ملغى",
  cancel: "إلغاء",
  finished: "مكتمل",
  phones: "ارقام الهاتف",
  name: "الاسم",
  phone_numbers: "أرقام الهاتف",
  patient_about: "ملاحظة حول المستفيد",
  national_number: "الرقم الوطني",
  city: "المدينة",
  cities: "المدن",
  area: "المنطقة",
  areas: "المناطق",
  ratings: "التقييمات",
  rating: "التقييم",
  add_rating: "إضافة تقييم",
  add_visit: "إضافة زيارة",
  add_disclosure: "إضافة كشف",
  filter: "فلترة",
  is_custom_rating: "تقييم مخصص ؟",
  the_custom_rating: "التقيم المخصص",
  custom_rating: "تقيم مخصص",
  visits: "الزيارات",
  added_successfully: "تمت الإضافة بنجاح",
  edited_successfully: "تم التعديل بنجاح",
  action_done_successfully: "تمة العملية بنجاح",
  something_went_wrong: "حصل خطأ ما",
  beneficiaries: "المتسفيدين",
  beneficiary: "المستفيد",
  employees: "الموظفين",
  employee: "الموظّف",
  add_beneficiary: "إضافة مستفيد",
  add_employee: "إضافة موظف",
  no_data_found: "لم يتم العثور على اي بيانات",
  beneficiary_doesnt_have_any_disclosure: "لايملك هذا المستفيد اي كشف",
  manager: "إداري",
  supervisor: "مشرف",
  scout: "كشّاف",
  the_scout: "الكشّاف",
  role: "المنصب",
  none: "لا يوجد",
  priority_degree: "درجة الأهمية",
  cant_be_completed: "لايمكن إكمالها",
  not_completed: "غير مكتملة",
  completed: "مكتملة",
  note: "ملاحظة",
  description: "الوصف",
  code: "الرمز",
  visit_result: "نتيجة الزيارة",
  visit_reason: "السبب",
  sync: "المزامنة",
  from_date: "من تاريخ",
  to_date: "الى تاريخ",
  search: "بحث",
  undelivered: "غير مسلّمة",
  city_management: "ادارة المدن",
  add_and_manage_cities: "اضافة وادارة المدن",
  search_city: "ابحث عن مدينة",
  no_cities_found: "لاتوجد اي مدينة",
  add_to_see: "اضف بيانات لتظهر هنا",
  add_city: "اضف مدينة",
  no_work_areas_found: "لاتوجد اي منطقة",
  edit_city: "تعديل مدينة",
  city_name: "اسم المدينة",
  local_not_found_error: "لم يتم العثور على بيانات لعرضها",
  // created_by: "تمّت الإضافة من قبل",
  // updated_by: "تمّ التعديل من قبل",
  by: "من قِبل",
  work_areas: "ادارة المناطق",
  work_areas_subtitle: "ادارة وتنظيم المناطق",
  search_work_area: "ابحث عن منطقة ...",
  work_area_name: "اسم المنطقة",
  edit_work_area: "تعديل المنطقة",
  add_work_area: "اضافة منطقة",
  ratings_management: "ادارة التقيمات",
  add_manage_ratings: "اضافة وادرة التقيمات",
  no_ratings_found: "لا اتوجد اي تقيمات",
  edit_rating: "تعديل التقيم",
  priority_degrees: "درجة الاهمية",
  add_manage_priority_degrees: "اضافة وادراة درجة الاهمية",
  search_priority_degree: "ابحث عن درجة اهمية....",
  edit_priority_degree: "تعديل درجة الاهمية",
  add_priority_degree: "اضافة درجة الاهمية",
  select_color_optional: "اختر لون",
  quick_access: "اختبار سريع",
  added_disclosures: "الكشوفات المضافة",
  completed_visits: "الزيارات المكتملة",
  not_completed_visits: "الزيارات غير المكتملة",
  couldnt_be_completed_visits: "الزيارات التي لم يمكن إكمالها",
  this_week: "هذا الاسبوع",
  this_month: "هذا الشهر",
  this_year: "هذه السنة",
  custom: "مخصّصّ",
  summary: "ملخّص",
  detailed: "مفصّل",
  time_period: "الفترة الزمنيّة",
  satistics_type: "نوع الإحصائية",
  home_page: "الصفحة الرئيسيّة",
  medicines: "الأدوية",
  med_form: "الاستخدام",
  dose_variants: "الجرعات",
  no_medicines_found: "لا يوجد ادوية",
  medicines_management: "ادارة الادوية",
  add_manage_medicines: "اضافة و ادارة الأدوية",
  search_med: "ابحث عن دواء ...",
  add_medicine: "اضافة دواء",
  edit_medicine: "تعديل دواء",
  select_one_or_more_doses: "اختر جرعة او اكثر",
  intake_frequency_per_day: "عدد مرات في اليوم",
  dose: "الجرعة",
  add_beneficiary_medicine: "اضافة دواء لمريض",
  edit_beneficiary_medicine: "تعديل دواء مريض",
  dose_per_intake: "معيار الجرعة",
  appointment_not_completed: "لم تتمّ المراجعة بعد",
  appointment_completed: "تمّت المراجعة",
  appointment_date: "تاريخ المراجعة",
  family_members: "أفراد العائلة",
  add_family_member: "اضافة فرد عائلة",
  edit_family_member: "تعديل فرد عائلة",
  birth_date: "تاريخ الميلاد",
  job_or_school: "عمل | مدرسة",
  gender: "الجنس",
  kinship: "القرابة",
  male: "ذكر",
  female: "انثى",
  kinship_partner: "شريك",
  kinship_child: "ابن",
  kinship_parent: "اهل",
  kinship_brother: "اخ",
  kinship_grandparent: "جد",
  kinship_grandchild: "حفيد",
  appointment: "مواعيد المراجعة",
  add_disclosure_appointment: "اضافة موعد زيارة",
  selected_date_cap_warning: "يوجد العديد من المراجعات في هذا اليوم !!!",
  select_appointment_date: "أختر يوم للمراجعة",
  edit_appointment_date: "تعديل يوم المراجعة",
  warning: "انتبه",
  appointment_warning_message:
    "تجنبا للضغط يفضل اختيار تاريخ باقل عدد من المراجعين",
};

export default STRINGS;
